### ISSUE TITLE
Field types for link

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#1547] opened 2017-09-28 23:17 UTC
there are generally so many filed types but do we have any specific "field" type for the links ort I should use the text or text area field type, but in the case when I am trying to save the links would this be safe(sanitized)? I need links to be saved through the customizer for social media Icons such as Facebook, Twitter etc?

**Comment by aristath** [comment] 2017-09-29 01:26
sure! Just use `'type' => 'url'`

To be fair it's not a separate field-type, it's a normal text-field using the `esc_url_raw` function for sanitization.

So you can use this:
```php
Kirki::add_field( 'kirki_demo', array(
	'type'     => 'url',
	'settings' => 'the_setting',
	'label'    => esc_attr__( 'URL', 'kirki-demo' ),
	'section'  => 'my_section',
	'default'  => '',
) );
```
Or this:

```php
Kirki::add_field( 'kirki_demo', array(
	'type'              => 'text',
	'settings'          => 'the_setting',
	'label'             => esc_attr__( 'URL', 'kirki-demo' ),
	'section'           => 'my_section',
	'default'           => '',
	'sanitize_callback' => 'esc_url_raw',
) );
```
They are identical, the 1st one is just a shortcut for the 2nd one. 😄

**Comment by maxviewup** [comment] 2017-10-24 13:42
Would be nice if there is an dedicated link field (like the WordPress WYSIWYG link editor that previews site posts and pages)

**Comment by aristath** [comment] 2017-11-05 11:58
@maxviewup that's a great idea, reopening this one and marking as a feature request.

**Comment by AdsonCicilioti** [comment] 2018-11-19 19:40
Does that make those suggestions for posts and existing pages?

**Comment by aristath** [comment] 2018-11-19 19:56
Yes

**Comment by DannyCooper** [comment] 2019-06-26 15:31
Duplicate of https://github.com/aristath/kirki/issues/1588

**Closed as completed by DannyCooper** 2019-06-26 15:31 UTC
Labels: feature
