### ISSUE TITLE
Javascript 'in' and 'contains' operators error when checking for value in array

### ISSUE THREAD

**Issue by rthvanesa** [themeum/kirki#1597] opened 2017-11-01 13:41 UTC
### Issue description:
I'm using a sortable field and a toggle field which is being displayed only when a specific item in the sortable field is visible.
I get the following error in console in the moment I make a change in the sortable field: 
_Uncaught TypeError: Cannot read property 'dependent_field' of undefined 
field-dependencies.js?ver=4.8.3:38_ 

I've checked the _field-dependencies.js_ file and I suspect the error has to do with _window.kirkiControlDependencies_ which is always undefined. 

My solution was to replace _window.kirkiControlDependencies[ extras[0] ][ extras[1] ]_ with a simple boolean variable and now it's working great. 

### Version used:
3.0.11 and develop

### Using theme_mods or options?
Theme mods

### Code to reproduce the issue (config + field(s))

```
Kirki::add_config( 'mytheme', array(
   'capability'        => 'edit_theme_options',
   'option_type'       => 'theme_mod',
   'disable_output'    => true,
) );

Kirki::add_section( 'my_section', array(
   'title'          => esc_attr__('Header Styles', 'my_textdomain' ),
   'priority'       => 10,
   'capability'     => 'edit_theme_options',
) );

add_action( 'init', function() {
   Kirki::add_field( 'mytheme', array(
      'type'        => 'sortable',
      'settings'    => 'sortable_field',
      'label'       => __( 'This is the label', 'my_textdomain' ),
      'section'     => 'my_section',
      'default'	  => array(),
      'choices'     => array( '36' => 'Option 1', '37' => 'Option 2', '38' => 'Option 3', '39' => 'Option 4'),
      'priority'    => 10,
   ) );
});

Kirki::add_field( 'mytheme', array(
   'type'        => 'toggle',
   'settings'    => 'dependent_field',
   'label'       => __( 'This is the toggle', 'my_textdomain' ),
   'section'     => 'my_section',
   'default'     => true,
   'priority'    => 10,
   'active_callback' => array(
      array(
         'setting'  => 'sortable_field',
         'operator' => 'in',
         'value'    => '37',
      ),
   )
) );
```
Hope this will be solved.
Thank you for your support!

**Comment by aristath** [comment] 2017-11-01 22:13
@rthvanesa can you please test with the latest develop branch?
There were lots of bugs in the last version due to some changes in the latest WP releases and most of them have been fixed here so this may have been fixed alongside the others.

**Comment by rthvanesa** [comment] 2017-11-02 07:52
I have tested with the develop branch and I got the same error.

**Comment by traian-s** [comment] 2017-11-02 08:51
Can confirm the issue and the fix. PHP callback works fine with in & contains, it's just the js one that is buggeed. I see there is also a pull request on the matter: #1515 

The issue is coming from `window.kirkiControlDependencies[ extras[0] ][ extras[1] ]` variable, this perhaps is a leftover variable from a previous version, as it's not initialized or referenced anywhere else, it's just being used as a temporary control variable - replacing it with a regular boolean makes the script work.

**Comment by aristath** [comment] 2017-11-04 11:45
I just pushed a commit that _should_ fix this (props @krishna19)

Can you guys please test this and let me know if the develop branch now works for you?

**Comment by traian-s** [comment] 2017-11-06 09:26
On the right track just a few changes needed:
- _isNumeric is not an underscores function, replace with _isNumber
- still using an object as boolean check on the _isObject branch

I've created a pull request for the remaining issues, and everything seems fine on my local tests: #1608 

Cheers

**Comment by aristath** [comment] 2017-11-06 09:32
Yup, you're right. Merged the branch and closing this one 👍 
Thanks @traian-s, I really appreciate the pull-request. It's been a long weekend with almost 50 commits

**Closed as completed by aristath** 2017-11-06 09:32 UTC
Labels: bug

**Comment by traian-s** [comment] 2017-11-06 10:15
Glad I could help :)
