### ISSUE TITLE
Panel description "display:none" problem

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#1115] opened 2016-09-13 06:03 UTC
### Issue description:

Panel description is hidden.
### Using theme_mods or options?

Both

![Image description](https://s14.postimg.org/6lgv108g1/Untitled_1.jpg)

**Comment by aristath** [comment] 2016-09-15 23:53
Marked as a bug, will get this one fixed in the next release 'cause I'll have to refactor panels & sections anyway to accomodate some changes in the next version of Core WP.

**Comment by aristath** [comment] 2016-09-17 14:11
Not a bug.
Descriptions in the customizer show if you click the ( ? ) icon.
This comes from WP-Core.

**Closed as completed by aristath** 2016-09-17 14:11 UTC
Labels: bug
