### ISSUE TITLE
Add more than 1 variant using Typography Control

### ISSUE THREAD

**Issue by chandranoor** [themeum/kirki#1114] opened 2016-09-11 15:13 UTC
### Issue description:

I wonder how to add more than 1 google fonts variant using kirki typo option?
That would be great if use multiple choices instead of dropdown option.
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
### Using theme_mods or options?

Options
### Code to reproduce the issue (config + field(s))

Kirki::add_field( 'my_config', array(
    'type'        => 'typography',
    'settings'    => 'my_setting',
    'label'       => esc_attr__( 'Control Label', 'kirki' ),
    'section'     => 'my_section',
    'default'     => array(
        'font-family'    => 'Roboto',
        'variant'        => 'regular',
        'font-size'      => '14px',
    ),
    'output'      => array(
        array(
            'element' => 'body',
        ),
    ),

The code above only load 1 variant.

https://fonts.google.com/specimen/Lora?selection.family=Roboto:400

maybe you can add a feature like this
example:
Kirki::add_field( 'my_config', array(
...
...
default => array(
       variant => array('regular','600italic'),
)

**Comment by aristath** [comment] 2017-05-20 13:06
Closing as duplicate of #992

**Closed as completed by aristath** 2017-05-20 13:06 UTC
Labels: feature, control:typography
