### ISSUE TITLE
Editor link button issue - followup

### ISSUE THREAD

**Issue by stev0n** [themeum/kirki#1159] opened 2016-11-14 14:46 UTC
### Issue description:
Further to my previous post - Editor - link button -not working #1144

I found that (in my case) the missing editor link/unlink popup and the button tool tips that were missing are just hidden underneath. The can be restored.
I added the below css code to kirki/assets/customizer.css

.wp-full-overlay {
	z-index:unset !important;
}

Hope this is helpful.

Regards

Steve

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

**Comment by aristath** [comment] 2016-11-20 10:42
@stev0n If I understand correctly, the issue you're seeing is caused by this file: https://github.com/aristath/kirki/blob/develop/assets/scss/controls/editor.scss
Can you please try modifying these lines and see if that fixes your issue? https://github.com/aristath/kirki/blob/develop/assets/css/customizer.css#L593-L611

**Comment by aristath** [comment] 2016-11-20 11:14
@stev0n I just pushed a commit in the development branch.

Can you please try pulling this one and see if that fixes your issue?

**Comment by stev0n** [comment] 2016-11-26 15:52
Hi
Unfortunately, this didn't work.
I will download 2.4.0 and see if this issue goes away.

thanks
steev

**Comment by aristath** [comment] 2016-11-26 15:58
2.4.0 is highly experimental and a lot of things don't work there.
I wouldn't use it if I were you... it's just used for internal development 'cause I'm rewriting a lot of things in the plugin

**Comment by stev0n** [comment] 2016-11-26 16:21
ah, ok, thankx

it’s definitely a z-index issue

what i see in firebug is that the mce tool-tip div (+3 other mce elements)  is being created outside of the  kirki_editor_pane div
and (i guess) are therefore not being effected buy the css settings as you intended.

if i manually (using firebug) set display to block and the z-index to 500000  the tool-tip becomes visible

<div id="mceu_43" class="mce-widget mce-tooltip mce-tooltip-n" role="presentation" style="left: 326px; top: 584px; display: block; z-index: 500000;">
<div class="mce-tooltip-arrow"></div>
<div class="mce-tooltip-inner">Italic</div>
</div>

Regards
	Steve

**Comment by rinkuyadav999** [comment] 2017-01-08 17:13
Nice let fix it here: https://github.com/aristath/kirki/issues/1046

**Comment by rinkuyadav999** [comment] 2017-01-11 10:38
https://github.com/aristath/kirki/pull/1246

**Comment by aristath** [comment] 2017-03-28 21:56
fixed in develop branch.

**Closed as completed by aristath** 2017-03-28 21:56 UTC
