### ISSUE TITLE
Feature request  add toggle / collapse state for typography field wrapper

### ISSUE THREAD

**Issue by MrAndreius** [themeum/kirki#1931] opened 2018-06-23 18:30 UTC
The default hide the wrapper with settings and open it by click
![133](https://user-images.githubusercontent.com/1025948/41812461-cbf34f00-772b-11e8-9ac1-e102f320baf3.png)

**Comment by toton333** [comment] 2018-06-29 07:57
yes, or for background type or button type(where there are a lot of controls like text, color, hover color, background color, href). Basically a new field type with label and different toggle icon options and the target id to collapse should work i think

**Comment by MrAndreius** [comment] 2018-06-29 18:03
@toton333 hmm ... Interesting idea. A field is a container that can include other fields by combining them into a configuration group

**Comment by niklasp** [comment] 2018-11-21 14:05
label feature request? #2026

**Comment by aristath** [comment] 2018-11-21 15:43
Closing as duplicate of https://github.com/aristath/kirki/issues/1833

**Closed as completed by aristath** 2018-11-21 15:43 UTC
Labels: duplicate
