### ISSUE TITLE
Google Fonts are broken after 3.0.39

### ISSUE THREAD

**Issue by DeoThemes** [themeum/kirki#2160] opened 2019-05-22 13:26 UTC
### Issue description:
After updating to version 3.0.39 Google fonts on one of my themes are broken. I was using CDN checkbox before, but now it's gone, and Kirki still tries to load local fonts from **wp-uploads**. The problem it's trying to load the fonts over http://, but my site is using https:// which creates mixed content error and as a result no fonts are loaded.

Live demo - https://demo.deothemes.com/lami/

Here is the example, Kirki is adding this, as you can see it's http:

`local('CantataOne-Regular'), url(http://demo.deothemes.com/lami/wp-content/uploads/2019/05/PlI5Fl60Nb5obNzNe2jslWxNvcc-2.woff) format('woff');}@font-face{font-display:swap;font-family:'Roboto';font-style:normal;font-weight:400;src:local('Roboto'), local('Roboto-Regular'), url(http://demo.deothemes.com/lami/wp-content/uploads/2019/05/KFOmCnqEu92Fr1Me5g-2.woff) format('woff');}`

I can only avoid this issue if I roll back to version 3.0.35

I think this is related issue - https://github.com/aristath/kirki/issues/2089

### Version used:
3.0.39

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment] 2019-06-01 07:13
Closing as duplicate of #2089

**Closed as completed by aristath** 2019-06-01 07:13 UTC
