### ISSUE TITLE
 Kirki::add_field was called incorrectly. Kirki fields should not be added on customize_register

### ISSUE THREAD

**Issue by VietBui93** [themeum/kirki#2142] opened 2019-04-19 04:04 UTC
### Issue description:
I have just install Kirki toolkit and go to customize my site. I received the error :

> Notice: Kirki::add_field was called incorrectly. Kirki fields should not be added on customize_register. Please add them directly, or on init. Please see Debugging in WordPress for more information. (This message was added in version 3.0.10.) in **/wp-includes/functions.php on line 4667**

I have really read about the same issue (https://github.com/aristath/kirki/issues/1920) but I am using version 3.0.39. It still appears this error. Please tell me about the solution to resolve my problem.

Thank you for any of your help.

### Version used: 3.0.39
I install on WordPress plugin

### Using theme_mods or options?

theme_mobs
### Code to reproduce the issue (config + field(s))
I have just installed not change anything

**Comment by aristath** [comment] 2019-04-19 15:29
> Notice: Kirki::add_field was called incorrectly. Kirki fields should not be added on customize_register. Please add them directly, or on init.

The error is pretty self-explanatory... Are you adding the fields inside a function or file that gets called via an action? If so, which action? Is it `customize_register`? If yes, then it shouldn't.

**Comment by VietBui93** [comment] 2019-04-22 08:53
@aristath Thank you for your response!!
I don't really know what reason but I guess :

`class WC_Shop_Customizer {

	/**
	 * Constructor.
	 */
	public function __construct() {
		add_action( 'customize_register', array( $this, 'add_sections' ) );
		add_action( 'customize_controls_print_styles', array( $this, 'add_styles' ) );
		add_action( 'customize_controls_print_scripts', array( $this, 'add_scripts' ), 30 );
		add_action( 'wp_enqueue_scripts', array( $this, 'add_frontend_scripts' ) );
	}

	/**
	 * Add settings to the customizer.
	 *
	 * @param WP_Customize_Manager $wp_customize Theme Customizer object.
	 */
	public function add_sections( $wp_customize ) {
		$wp_customize->add_panel( 'woocommerce', array(
			'priority'       => 200,
			'capability'     => 'manage_woocommerce',
			'theme_supports' => '',
			'title'          => __( 'WooCommerce', 'woocommerce' ),
		) );

		$this->add_store_notice_section( $wp_customize );
		$this->add_product_catalog_section( $wp_customize );
		$this->add_product_images_section( $wp_customize );
		$this->add_checkout_section( $wp_customize );
	}`

I only installed the recommend of the plugins that Colorlib said in Tyche theme. And I imported their demo files.  And I received like above.
If that is a reason, can you tell me about how to fix it?

**Comment by DannyCooper** [comment] 2019-06-14 10:41
This seems to be caused by the Tyche theme.

It creates a wrapper for Kirki - `Tyche_Kirki::add_field()` which it loads on `customize_register`.

This would need to be resolved in the theme. Maybe consider forwarding theme support to this thread.

**Closed as completed by DannyCooper** 2019-06-14 10:41 UTC
