### ISSUE TITLE
Customizer is missing with update to WordPress 4.9

### ISSUE THREAD

**Issue by JenniferVanderputten** [themeum/kirki#1647] opened 2017-11-18 13:31 UTC
### Issue description:

The customizer content screen is blank, all the customizer areas are missing from the menu except widgets, but when I click on widgets, it says that there are 5 available but cannot be accessed via the customizer.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)  Kirki Toolkit 3.0.15 (the plugin version on my WordPress site)

### Using theme_mods or options?
I don't know.  This site uses the Hemma theme, but I am not the theme author.  This problem simply happened when the site updated to WordPress 4.9.

### Code to reproduce the issue (config + field(s))
I have no idea, but here is what the dev console says:

Uncaught ReferenceError: kirkiAllFonts is not defined
    at f.getFonts (script.min.js?ver=3.0.15:1)
    at f.renderFontSelector (script.min.js?ver=3.0.15:1)
    at f.initKirkiControl (script.min.js?ver=3.0.15:1)
    at f.ready (script.min.js?ver=3.0.15:1)
    at Object.<anonymous> (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,customize-base,wp-a11y,wp-util,jquery-ui-core,customize-controls,jquery-ui-widget,jquery-u&load[]=i-mouse,jquery-ui-sortable,jquery-ui-draggable,jquery-ui-droppable,backbone,wp-backbone,jquery-ui-slider,jquery-touch-punch,iris&load[]=,wp-color-picker,wp-ajax-response,jquery-color,wp-lists,postbox,nav-menu,wp-codemirror&ver=4.9:31)
    at i (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,customize-base,wp-a11y,wp-util,jquery-ui-core,customize-controls,jquery-ui-widget,jquery-u&load[]=i-mouse,jquery-ui-sortable,jquery-ui-draggable,jquery-ui-droppable,backbone,wp-backbone,jquery-ui-slider,jquery-touch-punch,iris&load[]=,wp-color-picker,wp-ajax-response,jquery-color,wp-lists,postbox,nav-menu,wp-codemirror&ver=4.9:2)
    at Object.add [as done] (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,customize-base,wp-a11y,wp-util,jquery-ui-core,customize-controls,jquery-ui-widget,jquery-u&load[]=i-mouse,jquery-ui-sortable,jquery-ui-draggable,jquery-ui-droppable,backbone,wp-backbone,jquery-ui-slider,jquery-touch-punch,iris&load[]=,wp-color-picker,wp-ajax-response,jquery-color,wp-lists,postbox,nav-menu,wp-codemirror&ver=4.9:2)
    at f.initialize (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,customize-base,wp-a11y,wp-util,jquery-ui-core,customize-controls,jquery-ui-widget,jquery-u&load[]=i-mouse,jquery-ui-sortable,jquery-ui-draggable,jquery-ui-droppable,backbone,wp-backbone,jquery-ui-slider,jquery-touch-punch,iris&load[]=,wp-color-picker,wp-ajax-response,jquery-color,wp-lists,postbox,nav-menu,wp-codemirror&ver=4.9:31)
    at f.e.Class (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,customize-base,wp-a11y,wp-util,jquery-ui-core,customize-controls,jquery-ui-widget,jquery-u&load[]=i-mouse,jquery-ui-sortable,jquery-ui-draggable,jquery-ui-droppable,backbone,wp-backbone,jquery-ui-slider,jquery-touch-punch,iris&load[]=,wp-color-picker,wp-ajax-response,jquery-color,wp-lists,postbox,nav-menu,wp-codemirror&ver=4.9:16)
    at f [as constructor] (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,customize-base,wp-a11y,wp-util,jquery-ui-core,customize-controls,jquery-ui-widget,jquery-u&load[]=i-mouse,jquery-ui-sortable,jquery-ui-draggable,jquery-ui-droppable,backbone,wp-backbone,jquery-ui-slider,jquery-touch-punch,iris&load[]=,wp-color-picker,wp-ajax-response,jquery-color,wp-lists,postbox,nav-menu,wp-codemirror&ver=4.9:16)

**Comment by aristath** [comment] 2017-11-18 14:11
@JenniferVanderputten can you please try using the version attacked on my reply here and let me know if that fixes your issue?
Other users have reported that this fixes it for them, so if you can confirm that too I'll be one step closer to a 3.0.16 release. 👍 
As soon as you test this please let me know, and it it works ok for you then I'll update the plugin on wordpress.org 

[kirki.zip](https://github.com/aristath/kirki/files/1484644/kirki.zip)

**Comment by JenniferVanderputten** [comment] 2017-11-18 15:41
Will do!  I'll update here with the results :)

**Comment by webnight** [comment] 2017-11-18 18:35
sorry the update 3.0.16 dosent work on me template.
on the menue for customizer is blank 
<img width="1035" alt="bildschirmfoto 2017-11-18 um 19 29 10" src="https://user-images.githubusercontent.com/33789731/32983608-9b5ba7fa-cc97-11e7-92b9-a06d5e5c67e9.png">

**Comment by JenniferVanderputten** [comment] 2017-11-18 18:37
That fixed it!  Thank you so much, especially for such a quick turnaround!

**Comment by aristath** [comment] 2017-11-18 18:41
@JenniferVanderputten thanks for checking!
As soon as I resolve another issue with the code controls I'll be able to release an update 👍 

@webnight are you getting the same errors mentioned in the original post? Or do you get something different?
It should no longer be possible to get the same error with the version from the zip file I attached in my previous reply, did you try resetting your browser's cache and cookies?
Are you on WordPress 4.9?

**Comment by webnight** [comment] 2017-11-18 18:43
sorry me template dont have fixed with the 3.0.16 zip
im have the template http://preview.themeforest.net/item/modellic-woocommerce-booking-model-agency-wordpress-theme/full_screen_preview/16797802
and wordpress 4.9
visual composer (WPBakery Page Builder 5.4.4)

**Comment by webnight** [comment] 2017-11-18 18:55
and the editor get the " http error 500 "  


<img width="419" alt="bildschirmfoto 2017-11-18 um 19 53 14" src="https://user-images.githubusercontent.com/33789731/32983755-4b0cd10e-cc9a-11e7-8292-62747dd005a8.png">

**Comment by aristath** [comment] 2017-11-18 19:54
@webnight I'm afraid I can't support premium plugins because I don't have access to them or their code and I don't know what they are doing.

It may be Kirki's fault indeed, or it may be the theme's fault. No way for me to know.

For support on your premium theme please contact the theme developer. If they debug it and find out that kirki does indeed have a bug, then I'd be more than happy to help them fix the issue. 
But that can't be done without a proper examination of the theme's files from the developer first so that they may contact me with specific details on what it is they tried, what works, what doesn't and where the error comes from with specific code.

Since everyone else confirmed that this works both on this ticket and others, I'll go ahead and close this ticket releasing an update for the plugin. That should also allow the developer of your premium theme to test if it works directly. It might be a simple fix on their part.

**Closed as completed by aristath** 2017-11-18 19:54 UTC
