### ISSUE TITLE
Required not working

### ISSUE THREAD

**Issue by peazz** [themeum/kirki#471] opened 2015-11-04 21:19 UTC
Hey,

Great plugin! I have just started using your plugin direct from this repo as the wordpress SVN hasn't been updated in a while.

I am trying to use the required option to conditionally load fields based on a type=switch however, I cannot get it to work at all.

```
   /**
        *   BaseConfig - Inherited
        **/
        Kirki::add_config( 'basejump_kiri_config', array(
            'option_name'   => 'basejump_settings',
            'capability'    => 'edit_theme_options'
        ) );


           // Disable blog title
    Kirki::add_field( 'basejump_kiri_config', array(
        'settings' => 'enable_archive_title',
        'label'    => __( 'Enable Blog Archive Title', 'translation_domain' ),
        'section'  => 'basejump_blog_section',
        'type'     => 'switch',
        'default'  => true,
        'choices'     => array(
            'on'  => __( 'On', 'kirki' ),
            'off' => __( 'Off', 'kirki' ),
        ),
    ) );

    Kirki::add_field( 'basejump_kiri_config', array(
        'settings' => 'blog_archive_title',
        'label'    => __( 'Blog Archive Title', 'translation_domain' ),
        'section'  => 'basejump_blog_section',
        'type'     => 'text',
        'required'    => array(
            array(
                'setting'  => 'enable_archive_title',
                'operator' => '==',
                'value'    => true,
            ),
        ),
    ) );
```
##

**Comment by peazz** [comment] 2015-11-06 19:32
Still cant fix this and get it working.

**Comment by peazz** [comment] 2015-11-06 19:52
I have done some searching and it wont work with option arrays.

The moment I set an array name, it stops working :)

**Comment by pingram3541** [comment] 2015-11-06 22:43
Just confirmed this using the nested array and without it.  I'm using a select field and it's not working either.

Just curious if its also best when using this for visibility of customizer fields only (just field organization) and no need to store an actual value in the database to set transport to postMessage to kill the unnecessary refresh.

**Comment by peazz** [comment] 2015-11-07 01:37
i could see that being problematic. All use cases for my customizer would still require a UI refresh..an example would be switching header templates... Sometimes there is just a navbar, others a header and a navbar so need to conditionally show styling options however the UI still needs a refresh to show the template change.

@author - I changed from theme options and gave it an option name (to use an options array) and the required field instantly stops working.

For us using it for theme development using single options for 100 odd settings will get clunky and slow fast... It would be great if you can make this top priority, it's a great toolkit.

**Comment by reshogun** [comment] 2015-11-07 03:40
@peazz  do you have any UI problems with your toolkit? I mean like toggle has been rendered to checkbox etc?

**Comment by peazz** [comment] 2015-11-07 10:53
@reshogun Hey, no not having any problems like that but let me test.. I have been used the slider toggle and it shows fine.

**Comment by peazz** [comment] 2015-11-07 11:12
Here is a snippet of my customizer code..

```
/**
*   BaseConfig - Inherited
**/
Kirki::add_config( 'basejump_kiri_config', array(
    'option_name'   => 'basejump_settings',
    'capability'    => 'edit_theme_options'
) );


/**
*   Add Panel
**/
Kirki::add_panel( 'bj_design_panel', array(
    'priority'      => 21,
    'title'         => __( 'Design', 'BaseJump' ),
    'description'   => __( 'This panel contains settings that affect the sites layout.', 'HN' ),
) );

/**
*   Add Header Section
**/
Kirki::add_section( 'bj_panel_layout_section_header' , array(
    'title'      => __( 'Header', 'BaseJump' ),
    'description'    => __( '' ),
    'panel'   => 'bj_design_panel',
) );

/**
*   Add Option Toggle
**/
Kirki::add_field( 'basejump_kiri_config', array(
    'type'        => 'radio',
    'settings'    => 'header_layout_style',
    'label'       => __( 'Header Layout Style', 'kirki' ),
    'section'     => 'bj_panel_layout_section_header',
    'choices'     => array(
        'left'   => 'Left',
        'top-large'  => 'Top Large',
        'top-small' => 'Top Small',
        'off-canvas' => 'Off Canvas',

    ),
) );

/**
*   Add Fields
**/

Kirki::add_field( 'basejump_kiri_config', array(
    'settings' => 'header_bkg_color',
    'label'    => __( 'Header Background Color', 'section'),
    'section'  => 'bj_panel_layout_section_header',
    'type'     => 'color',
    'default'  => '#ffffff',
    'output'   => array(
        array(
            'element'  => 'header',
            'property' => 'background',
        )
    ),
) );

// h border color
Kirki::add_field( 'basejump_kiri_config', array(
    'settings' => 'header_border_color',
    'label'    => __( 'Header Border Color', 'section'),
    'section'  => 'bj_panel_layout_section_header',
    'type'     => 'color',
    'default'  => '#f1f1f3',
    'output'   => array(
        array(
            'element'  => 'header',
            'property' => 'border-color',
        )
    ),
) );

Kirki::add_field( 'basejump_kiri_config', array(
    'type'        => 'slider',
    'settings'    => 'header_border_width',
    'label'       => __( 'Header Border Width', 'kirki' ),
    'section'     => 'bj_panel_layout_section_header',
    'default'     => 1,
    'choices'     => array(
        'min'  => 0,
        'max'  => 100,
        'step' => 1
    ),
    'output'   => array(
        array(
            'element'  => 'header',
            'property' => 'border-width',
            'units'    => 'px',
        )
    ),
    'required'    => array(
        array(
            'setting'  => 'header_layout_style',
            'value'    => 'top-large',
            'operator' => '==',
        ),
    ),
) );
```

This is a big deal breaker for me, I am about ready to code my own solution :(

**Comment by pingram3541** [comment] 2015-11-07 16:48
I have color and alpha js_vars callbacks working but instead of 'output' use 'js_vars' and set 'transport' to 'postMessage'.  Your color options don't require the full refresh, let the built in js handle that.  Finally, add 'function' => 'css', to your 'js_vars' array as well so it knows to add inline styles vs html.  This is working for me as I also was not getting the wprefresh to work.  The huge limitation right now is it only adds the inline styles, so in the case of your headers, which is most likely different bits of html and php, I'm afraid those fields might be best keeping 'transport' default unless we had a true 'callback' option that was working (I think its also being looked at to be added to core), we could then update the html via js and our own admin_ajax pull.

**Comment by aristath** [comment] 2015-11-07 17:07
Hey guys!

Just a note...
I haven't been able to work on the plugin a lot these past few days 'cause I have to stay focused on my day job a bit... As soon as I have a few free hours I'll look into this.
It looks like using serialized options has a couple of outstanding issues that need to be resolved urgently.

In the meantime, if you're building a new theme I would advise you to use theme_mods instead of serialized options. They are a lot better performance-wise, they are autoloaded and have lots of benefits (settings are saved on a per-theme basis). More on theme_mods vs options vs serialized options here: https://github.com/aristath/kirki/wiki/theme_mods-vs-options

**Comment by peazz** [comment] 2015-11-08 14:55
Hey,

If you point me in the right direction file wise maybe I can help to solve this issue :)

**Comment by aristath** [comment] 2015-11-09 19:18
@peazz I suspect it's in this file: https://github.com/aristath/kirki/blob/master/includes/class-kirki-active-callback.php and you'll probably have to use this method in it so that it takes into account serialized settings: https://github.com/aristath/kirki/blob/master/includes/class-kirki-field-sanitize.php#L298-L324

**Comment by pingram3541** [comment] 2015-11-09 23:22
Ok looks like my problem is slightly different but may imply it has nothing to do with serialized arrays.  I used the example here: https://github.com/aristath/kirki/wiki/Controls-visibility

Basically I set a 'dummy' config with no options array like the example. I then built out a select drop-down field using the 'dummy' config and set a default option, "General Colors" along with several other "color" related menu choices such as "Header Colors", "Menu Colors"...

I then created color and color-alpha fields tying them to a different config because obviously I do want those values stored in the db.  I also had to change from using 'output' to 'js_vars' and also change to 'postMessage' because the refresh wasn't providing the live css even though when saving, the values were indeed being stored in my theme's options serialized array.

Lastly, for each of the color fields I defined the 'required' array to the specific value of my select fiels values such as "general_colors", "header_colors"...

However when I open the customizer and view the Theme Colors panel, I was expecting to see only the General Colors as that is the default value for the drop down field and all other colors should be hidden from view until the drop down changes.  Not the case, all colors are visible and the drop down does nothing when changed except trigger the customizer refresh.  No errors in the console.  Hopefully this longer report helps as I would think this needs to work before we take it a step further to check against an actual db dip on whether to display another field that requires a match to that value.

**Comment by pingram3541** [comment] 2015-11-09 23:47
Ok, I figured out my problem but not sure if this is going to work for me.

I noticed in the "controls visibility" demo that all 3 fields had the same config, the dummy config of which stores nothing to the db.  I changed one of my color fields to use the dummy config and now the select box controls whether it is visible or not.

However, this presents the problem in which I cannot store that color's value to the database unless I change the dummy config to an actual option or theme_mod, but then presents a new problem because I don't want to store the select box value to the database as its only present to provide the convenience of field visibility.

I must be missing something somewhere right?

**Comment by aristath** [comment] 2015-11-10 00:00
@pingram3541 You **have to** store it in the db.
Each control in the customizer is tied to a setting and each setting can either be a theme_mod or an option.
In order to show a control, you mush save its value in the db. That's the way the customizer works in WP-Core...
You could just add a setting like "color_controls_visibility" or something like that...

**Comment by pingram3541** [comment] 2015-11-10 00:51
Ok, I can live with that...initially was trying to avoid polluting the db with unnecessary values.

However back to square one.  When using a Kirki::add_config without an options array (like in the documentation example) the required select box does indeed control visibility as long as the fields share the same config but of course there would be no way to save any of those fields because the config doesn't define anything.  As soon as you give the config an options/theme_mods array, the required functionality is lost which I presume is what you were referring to in which the serialized arrays are breaking the functionality.  Sorry for the long round trip to get back where we already were.

**Comment by peazz** [comment] 2015-11-16 18:38
Hey Bud,

Not had a chance to look at this yet, been hectic with client work and crashed my car last week xD

Andy

**Comment by aristath** [comment] 2016-04-21 17:56
This has been fixed in a previous release.

**Closed as completed by aristath** 2016-04-21 17:56 UTC
Labels: bug, Unconfirmed
