### ISSUE TITLE
Removed apply_filters('kirki/config'... ?

### ISSUE THREAD

**Issue by pixedelic** [themeum/kirki#504] opened 2015-12-06 13:58 UTC
Hello, just updated to v.2.0.0... have you removed from the filter the ability of dequeue frontend css as for #276 ?

TIA

**Comment by aristath** [comment] 2015-12-06 14:34
Closing as a duplicate of https://github.com/aristath/kirki/issues/276

**Closed as completed by aristath** 2015-12-06 14:34 UTC
