### ISSUE TITLE
output of the develop kirki

### ISSUE THREAD

**Issue by replynone** [themeum/kirki#160] opened 2015-04-03 10:38 UTC
The normal kirki download does not work for me so I took the develop one.

"Using the output argument you can specify if you want Kirki to automatically generate and apply CSS for various elements of your page. This is defined as an array of arrays and each array contains a CSS element, a CSS property, and - optionally - a unit."

What I make from this is: you do not have to declare a value in the head <style type="text/css"></style>

But when I use the default setting:

``` php
$controls[] = array(
    'type'     => 'slider',
    'setting'  => 'my_setting',
    'label'    => __( 'Border width', 'translation_domain' ),
    'section'  => 'my_section',
    'default'  => 1,
    'priority' => 1,
    'choices'  => array(
        'min'  => 0,
        'max'  => 20,
        'step' => 1,
    ),
    'output' => array(
        array(
            'element'  => '.variable-top-border',
            'property' => 'border-top-width',
            'units'    => 'px',
        ),
        array(
            'element'  => '.variable-bottom-border',
            'property' => 'border-bottom-width',
            'units'    => 'px',
        ),
    ),
);
```

I do not see any changes in my console. Also changed the elements to an existing class, what im using in my css/html or the body element, nothing happens when saved. 

When using the php $value my_setting it does output a slider step, for example 9.
Am I missing something or?

Thanks for your help so far.

Edit: not using kirki as a plugin.

**Comment by aristath** [comment] 2015-04-03 14:43
I'm sorry but I don't understand what the problem is.... Can you please elaborate?

**Comment by replynone** [comment] 2015-04-08 12:47
Hi, sorry for the late response.

I see you made some nice updates :+1: 

What i meant was this. I do not get any custom <  style > in the < head > when using the <strong> 'output' => array </stong> ... in a $control[]

Because the kirki site says:
<i>Based on these values Kirki will then automatically generate the necessary CSS and properly enqueue it to the < head > of your document so that your changes take effect immediately without the need to write any additional code.</i>

Do i need to put something in the < head > or with a get_theme_mod?? Sorry i am not a php whizkid :smile: 

I can grab the changes in the value with a normal get_theme_mod, so it does save etc
<code>
$value = get_theme_mod( 'my_setting' );
echo  $value
</code>

I can create a function, something like this to output the css changes in the head but i do not think this is what you mean?:
<code><?php function kirki_css_custom() { ?>
< style > type="text/css"> .variable-bottom-border { border-bottom-width: <?php $value = get_theme_mod( 'my_setting' ); echo  $value ?>px;}</ style >
<?php } add_action ('wp_head','kirki_css_custom') ?></code>

**Comment by fovoc** [comment] 2015-04-22 18:35
Hey there,

I can confirm that this is a working condition, out of the box. No need for extra functions. You should have something like 
`<style id='kirki-styles-inline-css' type='text/css'>`
in your markup. Can you please grab the latest commit, just in case, and test again?

Cheers,
Dimitris

**Comment by aristath** [comment] 2015-05-24 14:20
@replynone are you still having an issue with this or is it safe to assume this has been fixed in the master branch?

**Comment by aristath** [comment] 2015-06-15 18:14
Closing due to inactivity.

If this issue still exists using the latest build from the github repo then please feel free to reopen this ticket.

**Closed as completed by aristath** 2015-06-15 18:14 UTC

**Comment by replynone** [comment] 2015-06-19 08:19
Hi, sorry for the late response.
Got the css to work, had a line in my functions.php what made the conflict.
