### ISSUE TITLE
Image Field type won't update automatically 

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#218] opened 2015-04-29 16:35 UTC
The image field type doesn't seem to trigger the refresh of the preview page. This is the only field where I've noticed this behaviour, so I was wondering if it is a bug or something im doing wrong.

Thanks.

**Comment by lmartins** [comment] 2015-04-29 19:43
After further testing, im noticing the image field is not the only one showing issues. I've also noticed it's not so much the case of not refreshing at all, it seems more that the refresh happens at the wrong time and the page shows the previous state.

If I add a image the page refreshes but still no image, if I then update the image the page reloads again but shows the first image. The cycle goes, showing the previous state after every refresh.

Im also seeing this with other fields like the image radio for example. I use it to control the layout of the page but again it seems out of sync.

Thanks.

**Comment by lmartins** [comment] 2015-05-06 13:49
Is it just me who are seeing this?

**Comment by aristath** [comment] 2015-06-15 19:03
@lmartins Hey there!

Sorry for the extreme delay on this one...
Are you still having this issue using the latest build?

**Comment by lmartins** [comment] 2015-06-18 19:14
Hi @aristath , no worries.
Yes, it still the same, it has been so for a while now.
Im using the WordPress.org version though, not sure if is that what you mean with latest build.

**Comment by aristath** [comment] 2015-06-18 19:29
@lmartins Can you please try with the master branch from the github repo?

**Comment by lmartins** [comment] 2015-06-18 19:35
Sure, just tested and it shows the same behaviour. It takes a "hard" refresh for the customiser interface to show the uploaded image.

**Comment by lmartins** [comment] 2015-06-19 08:27
Btw @aristath, with this version from Github I get a new warning:

```
Warning: Invalid argument supplied for foreach() in /srv/www/rulergy/htdocs/wp-content/plugins/kirki-master/includes/class-kirki-fonts-font-registry.php on line 263
```

**Comment by aristath** [comment] 2015-06-20 15:34
@lmartins can you please post the code you're using here so that I may try to replicate your issue?

**Comment by lmartins** [comment] 2015-06-20 21:37
Hey @aristath,
I'll try to simplify a test case, otherwise i'll need to send you the complete theme and you would need to install all the dependencies, etc.
I will build a simpler test case so we can isolate the problem.

**Comment by aristath** [comment] 2015-06-20 21:38
thanks... hopefully we'll be able to squash this bug too and get one step closer to releasing version 1.0 :)

**Comment by aristath** [comment] 2015-06-27 14:12
@lmartins any news on this one mate? 
Please try pulling the latest commits and test... I fixed a couple of bugs, I don't know if this issue was caused by one of them. 
If you can't figure this one out try sending me the whole theme.

**Comment by lmartins** [comment] 2015-06-29 09:04
Hey @aristath, im hoping to build a test case today. Sorry for the delay on this...

**Comment by lmartins** [comment] 2015-06-30 10:04
Hi @aristath i've just noticed that the API has changed quite a lot, im still using the prior way of declaring things. Before I send you anything, are the two APIs compatible?

**Comment by aristath** [comment] 2015-06-30 12:31
Yup, it's completely backwards-compatible. :)

**Comment by lmartins** [comment] 2015-07-05 15:33
Hi @aristath, much sorry about the delay here.

Can I have an email to send you my project files?

**Comment by aristath** [comment] 2015-07-05 15:34
@lmartins you should be able to find it in my github profile. :)

**Comment by lmartins** [comment] 2015-07-05 15:34
Jesus man, you're fast

**Comment by aristath** [comment] 2015-07-05 15:35
LOL I have notifications from this repo coming to a slack channel and I'm working on the plugin now... so I see all comments as they are posted. :wink:

**Comment by aristath** [comment] 2015-07-06 00:38
This turned out to be an issue with Timber.
If anyone else finds themselves having the same issue and you're using twig/timber, then please make sure you read this comment: https://github.com/jarednova/timber/issues/420#issuecomment-71017087

I'm closing this one for now, if you find that the issue still persists after making this modification then please don't hesitate to reopen this ticket and post an update on your current status.

Cheers!

**Closed as completed by aristath** 2015-07-06 00:38 UTC
