### ISSUE TITLE
Set custom post meta and WordPress editor in customize

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#927] opened 2016-04-24 18:55 UTC
### Issue description:

How to load WordPress editor in customize and how to set custom post meta.
### Version used:

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
2.3.1
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

1:- I want to know how to display WordPress visual editor (text area as visual editor). if it is already available, please tell me about this field.
2:- i want to set custom post meta using kirki toolkit. i think it is not available now. but it will great feature. because we can use kirki toolkit like **All in One options**. toolkit.

**Comment by aristath** [comment] 2016-04-26 07:59
I'm afraid we don't currently support post meta...
It's something we'll add sometime in the future I just don't have a date for that yet. Closing this one as a duplicate of https://github.com/aristath/kirki/issues/463
If you want there's some custom code in that post that you can try using.

As for using a wysiwyg field, simply set the `type` argument to `editor`.
However keep in mind that you can only have 1 editor in your customizer. If you create a 2nd one it won't work properly.
It's a known bug and we're working on it.

**Closed as completed** 2016-04-26 14:28 UTC
