### ISSUE TITLE
Issue when use camelCase in section id

### ISSUE THREAD

**Issue by Serpentsoft** [themeum/kirki#692] opened 2016-02-28 13:01 UTC
Hi pal,

I noticed that when i use camelCase in section id all section disappear but when name it with lowercase it works fine .. so after some tests i noticed that you perhaps convert section id to lowercase BUT you leave the section field inside add_field function without changes, so the section id not equal the field section id.

Example: 
GOOD: 
- add_section -> ID = 'camelCase'
- add_field -> Section = 'camelcase' // lowercase

BAD:
- add_section -> ID = 'camelCase'
- add_field -> Section = 'camelCase' // camelCase

Thanks for your awesome project.

**Comment by aristath** [comment] 2016-02-28 19:17
Great catch!

Can you please checkout the [develop branch](https://github.com/aristath/kirki/tree/develop) and let me know if the issue is fixed for you there?

**Comment by aristath** [comment] 2016-03-03 04:04
Closing this one, it has been fixed.

**Closed as completed by aristath** 2016-03-03 04:04 UTC
Labels: bug, URGENT
