### ISSUE TITLE
Google Fonts CSS output in Gutenberg editor on Multisite with HTTPS

### ISSUE THREAD

**Issue by nk-o** [themeum/kirki#2236] opened 2019-08-05 12:50 UTC
### Issue description:

Added Google Fonts with CSS output. I have tested several sites and looks like something wrong with the **main site** of multisite. I see this error when editing pages:

`
Mixed Content: The page at 'https://.../wp-admin/post.php?post=1242&action=edit' was loaded over HTTPS, but requested an insecure stylesheet 'http://.../?action=kirki-styles&editor=1&ver=3.0.44'. This request has been blocked; the content must be served over HTTPS.
`

In the source of this page styles URLs with HTTPS so seems like the problem in content of these dynamic styles:

![image](https://user-images.githubusercontent.com/14810891/62465063-b61f6900-b796-11e9-9313-6bc037133bc9.png)

When I switch on other sites of this multisite, I don't see this error and styles loaded fine.

### Version used:

Previously used Kirki 3.0.41 with no problems, but today I updated it to the latest version 3.0.44

### Using theme_mods or options?

theme_mods

### Code to reproduce the issue (config + field(s))

Actually, our themes have more typography options, but maybe these styles will be enough:

```php
if ( class_exists( 'Kirki' ) ) {
	Kirki::add_config( 'test_guten', [
		'capability'    => 'edit_theme_options',
		'option_type'   => 'theme_mod',
	] );

	Kirki::add_section( 'typography', [
		'title' => esc_html__( 'Typography', 'kirki' ),
		'priority' => 30,
	] );

	Kirki::add_field( 'test_guten', [
		'type'        => 'typography',
		'settings'    => 'typography_main_body',
		'label'       => esc_html__( 'Body Test', 'kirki' ),
		'section'     => 'typography',
		'default'     => [
			'font-family'    => 'Roboto',
			'variant'        => 'regular',
			'font-size'      => '14px',
			'line-height'    => '1.5',
		],
		'transport'   => 'auto',
		'output'      => [
			[
				'element' => 'body',
			],
			[
				'element' => '.edit-post-visual-editor.editor-styles-wrapper',
				'context' => [ 'editor' ],
			],
		],
	] );
}
```

**Comment by aristath** [comment] 2019-08-11 11:51
Hello @nk-o 
That stylesheet gets enqueued on https://github.com/aristath/kirki/blob/v3.0.44/modules/css/class-kirki-modules-css.php#L141-L146
As you an see there, we use the `site_url()` function so it should use the settings you've set in your dashboard.
Could you please make sure that your site's URL is set to use https and not http?

**Comment by nk-o** [comment] 2019-08-11 20:15
@aristath hi. With this URL everything is fine (it is https on my site, as I showed you on screenshot), but the problem seems like inside this style. I assume, there is a problem when used locally downloaded font files.

I can give you access to our demo site, so you can take a look.

**Comment by aristath** [comment] 2019-08-11 20:23
Ah ok, I see what the issue is...
This is definitely somehow related to the site's configuration, but I believe we can fix it by adding an extra check. 👍 
Marking as a bug andwill include a fix for this in the next release

**Closed as completed** 2021-12-28 13:05 UTC
Labels: bug
