### ISSUE TITLE
[feature] Kirki and selecting multiple images for gallery or slideshow

### ISSUE THREAD

**Issue by Alanimus** [themeum/kirki#1557] opened 2017-10-02 18:18 UTC
Sorry if this is not the place to post this, but I am not sure where else to ask for help or give suggestions for kirki. If there is a more appropriate place, let me know.

Is there a way to select multiple images say, if I want to create a slideshow? I have read some people possibly use the repeater, but wouldn't that mean you have to set a new image multiple times instead of using WP's built-in multi-select?

I know customizer has a gallery option, is something like that built into Kirki (or going to be)? Thanks!

**Comment by aristath** [comment] 2017-10-02 22:01
This will be implemented in version 3.1 👍

**Comment by amans2k** [comment] 2018-04-02 14:36
Hello,

I am using the customizer and wondering if image gallery feature implemented or not.
It is set to 3.1 milestone and we have 3.0.26 on GIT yet.

Any update on this?

The feature was: Allow multiple images selection on the image type.

Thanks,
Aman

**Comment by aristath** [comment] 2018-04-02 21:16
Hey there!
No, this has not yet been implemented.
I'll try to squeeze it in before 3.1, but definitely not 3.0.26

**Comment by NaveenKharwar** [comment] 2019-04-26 16:30
Hey there,
I want to know that multiple image select feature is now implemented or not? btw awesome work, Love Kirki.

Thank You

**Comment by DannyCooper** [comment] 2019-06-26 12:05
Duplicate of https://github.com/aristath/kirki/issues/905

**Closed as completed by DannyCooper** 2019-06-26 12:05 UTC
Labels: feature
