### ISSUE TITLE
Disable auto assign value when page change

### ISSUE THREAD

**Issue by jegbagus** [themeum/kirki#1022] opened 2016-06-08 10:41 UTC
This is not an issues, but this one is just a question that i unable to solve

When i change page on customize preview by clicking any link, all value from previous change assigned to new page by javascript (postmessage.js). how can i disable this behaviour? so there is no change will be made on new page, but it will only shown on original page where change been made.

i try to dive into the code, but it seems i lost. so i desperately need your help.
### Version used:

2.2.0
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

``` php
MyClass_Kirki::add_field( 'jnews', array (
    'type'      => 'color',
    'settings'  => 'mytheme_color',
    'label'     => __( 'Text Color', 'translation_domain' ),
    'section'   => 'custom_css',
    'default'   => 1,
    'priority'  => 1,
    'transport' => 'postMessage',
    'js_vars'   => array(
        array(
        'element'  => 'body',
        'function' => 'css',
        'property' => 'background-color',
        ),
        array(
        'redirect' => 'category_tag'
        )
    )`

```

**Comment by aristath** [comment] 2016-06-08 23:34
Closing as a duplicate of https://github.com/aristath/kirki/issues/1024

As mentioned there, I could not replicate the issue using that single field, so it looks to me like this is working fine.
If there's something wrong then perhaps it's because of some other code in your theme?

**Closed as completed by aristath** 2016-06-08 23:34 UTC
Labels: duplicate
