### ISSUE TITLE
Version 3.0.36 removes all downloaded fonts style

### ISSUE THREAD

**Issue by Oxibug** [themeum/kirki#2089] opened 2019-02-18 05:34 UTC
Hi Dude,

I think there's a fetal mistake happened in version 3.0.36, I was using download font locally to avoid CDN and minimizing issues, After upgrade all local fonts under the style id **kirki-local-webfonts** removed and of course all theme's design destroyed, The fonts still in its path [uploads/websfonts/xxx] but it doesn't load like old versions.

I think you must leave old functionality because of our users always upgrade plugin and we cannot help them and the documentation is not clear enough in some issues.

Thanks for the great project

### Version used:
3.0.36

**Comment by aristath** [comment] 2019-02-18 16:59
@Oxibug I can't replicate the issue, everything seems to be working fine on my end and in more than 10000 downloads so far you're the only one to report any issue... 
The old implementation was bad for performance and it was breaking in combination with some caching plugins, it had to change. 
Could you perhaps post a link to site that has an issue like that? Are there any caching plugins enabled on that site? Which theme is it? Is there any chance of me having access to that site to debug? You can contact me via email if you need to send private credentials.

**Comment by DeoThemes** [comment] 2019-05-22 05:05
I think I'm having the same issue. I was using the old method with CDN checkbox, but after updating to latest versions this checkbox is now gone but the fonts are still trying to load from **uploads** folder over http:// even if my site is https://. As a result broken fonts on the website - https://demo.deothemes.com/lami/

Currently I found the only fix is to use version **3.0.35.3**
How to fix it?

**Comment by DannyCooper** [comment] 2019-05-31 18:21
The local font URLs are cached in a transient, that means if your site is set to http:// and then you change to https://, the plugin will still use http for sometime.

If you can't clear the transient, try changing a font to see if it fixes the issue.

**Comment by aristath** [comment] 2019-06-01 07:16
@DeoThemes I checked your site and it looks fine now so as @DannyCooper mentioned this was probably due to some cache. I can see the font files get loaded locally instead of the Google CDN and judging from the page-source the plugin version used is newer than v3.0.35
Is this still an issue for you?

**Comment by DeoThemes** [comment] 2019-06-01 07:18
> @DeoThemes I checked your site and it looks fine now so as @DannyCooper mentioned this was probably due to some cache. I can see the font files get loaded locally instead of the Google CDN and judging from the page-source the plugin version used is newer than v3.0.35
> Is this still an issue for you?

I see now that the issue is gone, I'm using 3.0.39. How long does the transient last?
Thanks.

**Comment by DannyCooper** [comment] 2019-06-02 09:55
@DeoThemes 7 days

https://github.com/aristath/kirki/blob/2ad0b2f6ddc4b637cbf03acaf36e10b37f602173/packages/kirki-framework/module-webfonts/src/Webfonts/Embed.php#L201

**Comment by DannyCooper** [comment] 2019-06-13 10:21
Fixed in v3.0.41 by using protocol-agnostic URLs.

**Closed as completed by DannyCooper** 2019-06-13 10:21 UTC
