### ISSUE TITLE
Automating postMessage for composite fields

### ISSUE THREAD

**Issue by allysonsouza** [themeum/kirki#694] opened 2016-02-28 14:51 UTC
It's possible to use automatic postMessage for composite fields like Typography field? If yes, how could I do this?
##

**Comment by aristath** [comment] 2016-02-28 16:00
We're working on adding postMessage support to other composite fields, however the typography field has special requirements.
The problem with the typography field is that it it doesn't only change the font-weight, height, size etc of your typography, but also the font-family.
Font-families from google-fonts require us to change the actual markup of the page, not just the CSS. We have to re-load the fonts and change the request we make to the Google API. This can't work without refreshing the page, which is why in typography fields we're forcing a refresh.

I'm currently rebuilding the typography control in the develop branch and perhaps I'll be able to add partial support for postMessage (perhaps I can make it work for fields like the font-size, color etc) but I can't make any promises at this point.

**Comment by allysonsouza** [comment] 2016-02-29 02:49
Thanks for the reply @aristath, I understand the complexity of this using Google Fonts. Anyway, postMessage to fields such as font-size and color at least, will be very nice! :+1:

**Comment by aristath** [comment] 2016-03-04 03:12
@allysonsouza I started implementing this but unfortunately another issue made my attempts futile.
No matter what I did, the first couple of changes were applied via postMessage normally, and then this issue would kick in and mess things up: https://github.com/aristath/kirki/issues/717

So until someone helps us resolve that one, this will have to wait

I've been trying to address that issue for days without success so at this point I just set up a community-backed bounty and hope someone more skillful than myself with JS can find a solution, or that enough people pitch in a bounty to make resolving this issue more appealing to devs.

That being said, I figured out how to do the auto-postMessage for typography controls and they're pretty awesome - when they work.

**Comment by manuelmoreale** [comment] 2016-04-17 12:17
Maybe my last comment on the #717 can help @aristath find where the problem is and allow him to implement postMessages in the typography field. I'm coding a new theme were I have quite a few of those and would be awesome to have live preview for color, font size, line height and text align.

**Comment by manuelmoreale** [comment] 2016-04-18 06:20
@aristath now that #717 has been fixed any idea when you'll be able to implement/solve this one? Asking because I'm putting the last touch on a new theme and if you're going to release a new version soon I'll wait and change the structure of my fields since I now have a bunch of fields separated from the main typography field only to give users live preview :)

**Comment by aristath** [comment] 2016-11-20 09:14
This has been fixed.
Using `'transport' => 'auto'` in typography controls has the desired result now.

**Closed as completed by aristath** 2016-11-20 09:14 UTC
Labels: feature
