### ISSUE TITLE
Double units value (pxpx) in letter-spacing field after save and returning to section

### ISSUE THREAD

**Issue by carasmo** [themeum/kirki#862] opened 2016-04-09 14:35 UTC
### Issue description:

Double units value (pxpx) in letter-spacing field after save and returning to section. See image:

![screen shot 2016-04-09 at 10 36 53 am](https://cloud.githubusercontent.com/assets/1124594/14404241/021ee048-fe3f-11e5-9b24-ba17b0f570cf.png)
### Version used:

2.2.10
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

```
Sidewave_Kirki::add_field( 'sidewave_theme', array(
    'settings'    => 'site_description_style',
    'label'       => esc_attr__( 'Site Description Style', $GLOBALS['text-domain'] ),
    'section'     => 'header_site_description',
    'priority'    => 1,
    'type'        => 'typography',
    'description' => esc_attr__( 'Choose the same font as the body or headline. For fewer http: requests, choose the same font-family as the body or headlines.', $GLOBALS['text-domain'] ),
    'default'     => array(
        'font-family'    => 'Lora',
        'font-size'      => '14px',
        'variant'        => 'italic',
        'letter-spacing' => '0',
        'text-transform' => 'none',
        'line-height'    => '1.4',
    ),
    'output' => array(
        array(
            'element' => '.site-description',
        ),
    ),
) );
```

**Comment by aristath** [comment] 2016-04-09 16:42
Closing as a duplicate of #842

**Closed as completed by aristath** 2016-04-09 16:42 UTC
Labels: duplicate

**Comment by carasmo** [comment] 2016-04-09 16:46
Sorry didn't see the duplicate. Thanks!
