### ISSUE TITLE
Background field type automatically activating Publish button upon entering customizer

### ISSUE THREAD

**Issue by toton333** [themeum/kirki#1938] opened 2018-07-02 08:03 UTC
### Issue description:
The customizer's publish button always staying activated. Even if nothing has been changed, if you try to close customizer, pop up for exit confirmation is appearing. By trial and error i found out it is the background field type that is causing it.

### Version used:
Latest

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'airspace_kirki_config_id', array(
	'type'        => 'background',
	'settings'    => 'ideas_image',
	'label'       => esc_attr__( '' , 'airspace'),
	'section'     => 'frontpage_section2',
	'transport'   => 'auto',	
	'default'	 => array(
		'background-color'		 => 'rgba(20,20,20,.8)',
		'background-image'		 => '',
		'background-repeat'		 => 'no-repeat',
		'background-position'	 => 'center center',
		'background-size'		 => 'cover',
		'background-attachment'	 => 'fixed',
	),	
	'output'     => array(
          array(
            'element' => '.bg-2',

          )

	)
) );
```

**Comment by aristath** [comment] 2018-07-12 21:04
Yeah, this has been annoying me for quite some time.
Marking this as a bug and adding to the 3.0.34 milestone, though   can't promise it'll make it in this release. It's been an annoyance for sure, but doesn't cause any actual problems so it's not as urgent as other issues that may actually be causing more important issues. 👍

**Comment by seventhqueen** [comment] 2018-07-31 14:11
I can confirm that if you have a background field added, when opening the customizer the Publish button gets activated and it somehow will think that the field value is changed but it is not. 

You can check it by adding this snippet of code and it will say that the fields are changed, even at the first open of the customizer: 
```
if ( is_customize_preview() ) {
	if ( isset( $_POST['customized'] ) && ! empty( $_POST['customized'] ) && $_POST['customized'] != '{}' ) {
		var_dump($_POST['customized']);exit;
	}
}
```

If you want to check for some changed fields and do some compiling then it will not work as expected. 

Thanks

**Comment by seventhqueen** [comment] 2018-07-31 14:12
Also it is possible to relate to this issue too [https://github.com/aristath/kirki/issues/1942](https://github.com/aristath/kirki/issues/1942)

**Comment by aristath** [comment] 2018-08-23 15:36
Closing as a duplicate of #1942 
The problem is that color controls trigger a change event, and that affects complex controls like typography, background & multicolor.

**Closed as completed by aristath** 2018-08-23 15:36 UTC
Labels: bug
