### ISSUE TITLE
Typography Field Issue

### ISSUE THREAD

**Issue by rinkuyadav999** [themeum/kirki#1952] opened 2018-07-31 05:25 UTC
### Issue description:

'Published' button change to 'Publish' by opening Typography section. without any change in settings.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

3.0.33

### Using theme_mods or options?

theme_mods 

### Code to reproduce the issue (config + field(s))

```
Kirki::add_section( 'typography', array(
	'title'          => esc_attr__( 'Typography', 'tt' ),
	'capability'     => 'edit_theme_options',
) );

Kirki::add_field( 'tt_config', array(
	'type'        => 'typography',
	'settings'    => 'typo_body',
	'label'       => esc_attr__( 'Body Typography', 'tt' ),
	'section'     => 'typography',
	'default'     => array(
		'font-family'    => 'Lora',
		'variant'        => 'regular',
		'font-size'      => '14px',
	),
	'output'      => array(
		array(
			'element' => 'body',
		),
	),
	'transport' => 'auto',
) );

Kirki::add_field( 'tt_config', array(
	'type'        => 'typography',
	'settings'    => 'sitetitle_typo',
	'label'       => esc_attr__( 'Site Title Typography', 'tt' ),
	'section'     => 'typography',
	'default'     => array(
		'font-family'    => 'Fauna One',
		'variant'        => 'regular',
		'font-size'      => '22px',
		'line-height'    => '1.1',
		'letter-spacing' => '0',
		'text-transform' => 'inherit'
	),
	'output'      => array(
		array(
			'element' => '.site-branding-text .site-title a',
		),
	),
	'transport' => 'auto',
) );
```

**Comment by aristath** [comment] 2018-08-23 15:36
Closing as a duplicate of #1942 
The problem is that color controls trigger a change event, and that affects complex controls like typography, background & multicolor.

**Closed as completed by aristath** 2018-08-23 15:36 UTC
