### ISSUE TITLE
Typography error: Undefined index: font-family

### ISSUE THREAD

**Issue by DeoThemes** [themeum/kirki#1916] opened 2018-06-05 07:03 UTC
### Issue description:
I had the Typography field before to select from Google fonts with a default font-family settings:

```
	// Headings typography control
	Kirki::add_field( 'deo_config', array(
		'type'        => 'typography',
		'settings'    => 'deo_headings_typography',
		'label'       => esc_html__( 'Headings Typography', 'meridia' ),
		'description' => esc_html__( 'Select the general headings options for your site.', 'meridia' ),
		'help'        => esc_html__( 'The typography options you set here apply to all headings on your site.', 'meridia' ),
		'section'     => 'deo_typography',
		'priority'    => 10,
		'default'     => array(
				'font-family'    => 'Raleway',
				'font-weight'    => '600',
				'line-height'    => '1.3',    
		),
		'choices'  => array(
				'variant' => array(
						'regular',
						'600',
				),
		),
		'output' => array(
				array(
						'element' => $selector['headings'],
				),
		)
	));
```

Now I want to keep only controls to select font size and remove Google fonts control.
After deleting this Typography control the following error is showing:
**Notice: Undefined index: font-family in C:\MAMP\htdocs\wp_margin\wp-content\plugins\kirki\modules\webfonts\class-kirki-fonts-google.php on line 133**

### Version used:
3.0.33

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

```
	// Config
	Kirki::add_config( 'deo_config', array(
		'capability'    => 'edit_theme_options',
		'option_type'   => 'theme_mod',
		'option_name'   => 'deo_config'
	) );

	// H1 control
	Kirki::add_field( 'deo_config', array(
		'type'        => 'typography',
		'settings'    => 'deo_headings_h1',
		'label'       => esc_html__( 'H1 Headings', 'margin' ),
		'section'     => 'deo_typography',
		'priority'    => 10,
		'default'     => array(
			'font-size'      => '40px'
		),
		'output' => array(
			array(
				'element' => $selector['h1'],
			),
		)
	));
```

**Comment by aristath** [comment] 2018-06-06 21:28
I don't understand... If you don't want to use a font-family, then why use a typography control? If all you want to do is control the font-size then a `dimension` control is a lot better. Typography controls are built around the font-family selectors

**Comment by DeoThemes** [comment] 2018-06-07 01:59
Yes, it makes sense. But can I use output array with all h1 selectors on dimension control? Without using inline style. Seems like it's not working this way.

UPD:
Another scenario. I returned this settings that controls font-family for all headings, now I still have notice message _Undefined index: font-family_

**Comment by aristath** [comment] 2018-08-23 17:50
Closing as a duplicate of #1797, this should be working fine now in the develop branch.

**Closed as completed by aristath** 2018-08-23 17:50 UTC
Labels: bug
