### ISSUE TITLE
Codemirror error when on "option" mode (v2.3.0)

### ISSUE THREAD

**Issue by daviedR** [themeum/kirki#878] opened 2016-04-12 03:13 UTC
Hi Ari,

I found something interesting. When I changed my `option_type` to `option` (instead of `theme_mod`), I got this error when using the `code` field, which makes the whole Customizer not working.

http://pasteboard.co/7AaK6Zi.png

But when I was on `theme_mod` mode, it works fine, no errors shown.

**Comment by aristath** [comment] 2016-04-12 03:35
have you checked the develop branch?
I believe this is a duplicate of https://github.com/aristath/kirki/issues/874

**Closed as completed** 2016-04-12 23:51 UTC
Labels: bug, duplicate
