### ISSUE TITLE
Image field uploads other extensions also

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#1123] opened 2016-09-16 10:35 UTC
### Issue description:

When i upload or select file from 'type => image' it should only allow to select and upload image files but i can upload and select other extensions also. Should this be happening ??? If yes then why we need "type => image" and "type => upload".

**Comment by aristath** [comment] 2016-09-16 11:07
Marked as a bug, will be fixed in the next release.

**Comment by aristath** [comment] 2016-09-17 15:20
Not a bug.
Image controls use the WordPress-Core `WP_Customize_Image_Control` control and have no control over it (yet).

**Closed as completed by aristath** 2016-09-17 15:20 UTC
Labels: bug
