### ISSUE TITLE
Error in footer

### ISSUE THREAD

**Issue by qerrapress** [themeum/kirki#569] opened 2016-01-18 05:23 UTC
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Kirki_Customizer_Scripts_Loading' does not have a method 'customizer_scripts'

**Comment by doitmax** [comment] 2016-01-18 06:59
Yep, can confirm this problem.

**Comment by lmartins** [comment] 2016-01-18 09:55
Was about to report the same thing. It is a warning and will not break your site I believe. Seems to be related to the latest update.

**Comment by x-bull** [comment] 2016-01-18 14:33
I can confirm this error. Since 2.0.6 version

**Comment by aristath** [comment] 2016-01-18 21:59
duplicate of #573, already fixed.
I'll release a bugfix update in a couple of hours that will include this fix.

**Closed as completed by aristath** 2016-01-18 21:59 UTC

**Comment by aristath** [comment] 2016-01-18 22:26
2.0.7 released, this should be fixed now.
