### ISSUE TITLE
Sortable select field ( select2 multiple select)

### ISSUE THREAD

**Issue by Qodux** [themeum/kirki#1758] opened 2018-01-19 11:11 UTC
Hey there,

In older versions of the plugin where you used selectize script for kirki select field, the select field options were sortable. That was very useful, for example I have a theme customizer option for post meta. The user could choose between data, author, categories, comments and views meta and these were sortable. This way, users could choose to display author first or categories and so on. This is just an example but this could be helpful in any other ways. 

With the new Select2 script this is not possible by default, because Select2 does not, itself, provide the necessary code to perform dragging and dropping. I found an example here: http://select2.github.io/select2/#drag_drop, but seems that Select2 should be attached to a hidden input field. Also here: https://github.com/select2/select2/issues/1190, is a possible solution (https://github.com/vafour/select2-sortable).

Could you implement dragging and dropping for multiple select field using one of the above solutions, or probably you'll find a better one?

Thanks for your time,
Regards!

**Comment by aristath** [comment] 2018-01-22 20:51
There's a lready a feature request for that, closing as a duplicate of https://github.com/aristath/kirki/issues/1528

**Closed as completed by aristath** 2018-01-22 20:51 UTC
