### ISSUE TITLE
Google fonts still aren't loading correctly

### ISSUE THREAD

**Issue by Slobork** [themeum/kirki#1384] opened 2017-06-19 12:26 UTC
Hi,

@aristath this is the duplicate of the #1377 issue. Still, since you've closed it I do not have other way than to open a new issue, so that you're able to notice it. 

However, I've updated with the new comment on the original thread explaining the problem further. Please do continue there, you can actually close this one.

**Comment by aristath** [comment] 2017-06-19 16:35
Closing as a duplicate of #1377

**Closed as completed by aristath** 2017-06-19 16:35 UTC
