### ISSUE TITLE
Active Callback Not Yet Fixed

### ISSUE THREAD

**Issue by dtmgs** [themeum/kirki#1289] opened 2017-04-01 06:39 UTC
### https://github.com/aristath/kirki/issues/1286

Not yet fixed

http://recordit.co/FzuuRKfuh6

http://prnt.sc/eq7qt9

**Comment by aristath** [comment] 2017-04-01 11:20
Closing as duplicate of #1286 
Please avoid creating new tickets for the same issue.
Instead you can reopen the old one.

**Closed as completed by aristath** 2017-04-01 11:20 UTC
