### ISSUE TITLE
Nested panel are not working.

### ISSUE THREAD

**Issue by nazim848** [themeum/kirki#1973] opened 2018-09-04 01:29 UTC
### Issue description:

When I am trying to nest a panel it's not working.
Please see the codes.

### Version used:

3.0.33

### Using theme_mods or options?

theme_mods

### Code to reproduce the issue (config + field(s))

Kirki::add_panel('ipage_topbar_panel', array(
	    'priority'  => 90,
	    'title'     => esc_attr__('Topbar Main', 'ipage'),
	));

Kirki::add_panel('ipage_topbar_sub_panel', array(
	    'priority'  => 12,
	    'title'     => esc_attr__('Topbar Sub', 'ipage'),
	    'panel'     => 'ipage_topbar_panel',
	)); 

Kirki::add_section('ipage_topbar_section', array(
	    'priority'  => 118,
	    'title'     => esc_attr__('Topbar setting', 'ipage'),
	    'panel'     => 'ipage_topbar_sub_panel',
    ) );

Kirki::add_field( 'ipage-config', array(
	'type'     => 'text',
	'settings' => 'email',
	'label'    => __( 'Email', 'ipage' ),
	'section'  => 'ipage_topbar_section',
	'default'  => esc_attr__( 'info@domain.com', 'ipage' ),
	'priority' => 13,
) );

**Comment by aristath** [comment] 2018-09-06 15:20
Closing as a duplicate of #1972

**Closed as completed by aristath** 2018-09-06 15:20 UTC
