### ISSUE TITLE
Switch control doesn't work with required setting

### ISSUE THREAD

**Issue by padalec** [themeum/kirki#67] opened 2015-03-05 12:21 UTC
Hi,
I try to create dependency field so I try to use required setting for field but fields doesn't show when switch is turn on. This is my controls array:

<pre>
[20] => Array
        (
            [type] => checkbox
            [setting] => topbar_visible
            [mode] => switch
            [label] => Turn on top bar
            [default] => on
            [section] => topbar
        )

    [21] => Array
        (
            [type] => text
            [setting] => topbar_welcome_text
            [label] => Welcome text
            [default] => 
            [required] => Array
                (
                    [topbar_visible] => on
                )

            [section] => topbar
        )

    [22] => Array
        (
            [type] => checkbox
            [setting] => topbar_show_address
            [mode] => switch
            [label] => Show company address
            [default] => off
            [required] => Array
                (
                    [topbar_visible] => on
                )

            [section] => topbar
        )
</pre>

**Comment by briancwelch** [comment] 2015-03-05 14:55
Hello there.  We had fixed the bug when requiring controls a few commits ago.  Are you using the latest Github commit?  If not, could you try pulling that and see if it works for you?

Additionally, when toggling an option that has a required argument, sometimes it is necessary to refresh the customizer page.

**Comment by padalec** [comment] 2015-03-06 09:47
Hi,
yes I have the newest version of kirki. I refreshed page but this doesn't help to.

**Comment by padalec** [comment] 2015-03-06 09:53
Hmm I see the version from pulling is different then 'download zip' button. With one is correct?

**Comment by padalec** [comment] 2015-03-06 10:56
I founded this js code in source: 

``` javascript
jQuery(document).ready(function($) {
  $( '[id="customize-control-copyright_text"]' ).fadeOut(300);
  $( "#input_copyright_enabled input" ).each(function(){
  $(this).click(function(){
  if ( $(this).val() == "OFF" ) {
     $( '[id="customize-control-copyright_text"]' ).fadeIn(300);
  } else {
    $( '[id="customize-control-copyright_text"]' ).fadeOut(300);
  }
});
if ( $(this).val() == "OFF" ) {
   $( '[id="customize-control-copyright_text"]' ).fadeIn(300);
} else {
   $( '[id="customize-control-copyright_text"]' ).fadeOut(300);
}
});
});
```

I see that you looking for '#input_copyright_enabled input' ID but field what I want to show have id: customize-control-copyright_enabled

**Comment by padalec** [comment] 2015-03-06 11:27
It's looks like you looking only for $( "#input_<?php echo $id; ?> input" ) input container so this only will works with radio or checkbox but didn't with toggle or switch control

**Comment by padalec** [comment] 2015-03-10 13:23
Hi,
somethings new about my problem?

**Comment by briancwelch** [comment] 2015-03-15 14:11
We believe this to be fixed in v.7x.  Can you please pull the latest from source and let us know if the issue still remains for you?

**Comment by aristath** [comment] 2015-03-15 16:15
Closing this one as a duplicate of #7, we're going to rebuild the way required arguments work.

**Closed as completed by aristath** 2015-03-15 16:15 UTC
