### ISSUE TITLE
Selective refreshes not working with repeater field 

### ISSUE THREAD

**Issue by Imonthemes** [themeum/kirki#1264] opened 2017-02-14 09:58 UTC
### Issue description:
Selective refreshes not working with repeater field 

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

Development version 

### Using theme_mods or options?

theme_mods

**Comment by tivnet** [comment] 2017-02-15 22:20
Same as https://github.com/aristath/kirki/issues/1227 ?

**Comment by aristath** [comment] 2017-03-04 09:26
Closing as a duplicate of #1227 

This is still a work in progress, repeater fields are a bit more complicated than others

**Closed as completed** 2017-03-28 21:43 UTC
