### ISSUE TITLE
Date and Time picker for Kirki code

### ISSUE THREAD

**Issue by alhoseany** [themeum/kirki#765] opened 2016-03-25 02:04 UTC
### Issue description:

this is a new control i created for wordpress customizer for date and time selection.
### Version used:

Version 2.2.4 
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

functions.php 
`add_action( 'customize_register', function( $wp_customize ) {
    /**
     \* The Date/Time control class
     */
    class Kirki_Controls_Date_Time_Control extends WP_Customize_Control {
        public $type = 'date_Time';

```
    /**
     * Enqueue the styles and scripts
     */
    public function enqueue()
    {
        wp_enqueue_style( 'datetimepicker-style', get_template_directory_uri() . '/inc/datetimepicker/jquery.datetimepicker.css');
        wp_enqueue_style( 'datetimepicker-custom-style', get_template_directory_uri() . '/inc/datetimepicker/custom.css');
        wp_enqueue_script( 'datetimepicker-script', get_template_directory_uri() . '/inc/datetimepicker/jquery.datetimepicker.full.min.js', array('jquery'), '1.0.0', true );
        wp_enqueue_script( 'datetimepicker-custom-script', get_template_directory_uri() . '/inc/datetimepicker/custom.js', array('datetimepicker-script'), '1.0.0', true );
    }
    /**
     * Render the content on the theme customizer page
     */
    public function render_content() {
        ?>
        <label>
            <span class="customize-control-title"><?php echo esc_html( $this->label ); ?></span>
            <div class="customize-control-content">
                <input type="text" id="<?php echo $this->id; ?>" name="<?php echo $this->id; ?>" value="<?php echo $this->value(); ?>" data-customize-setting-link="<?php echo $this->id; ?>"  class="datetimepicker" >
            </div>
        </label>
        <?php
    }
}
// Register our custom control with Kirki
add_filter( 'kirki/control_types', function( $controls ) {
    $controls['date_Time'] = 'Kirki_Controls_Date_Time_Control';
    return $controls;
} );
```

} );`

https://github.com/xdan/datetimepicker/blob/master/jquery.datetimepicker.css
https://github.com/xdan/datetimepicker/blob/master/jquery.datetimepicker.min.js

custom.css 

`.xdsoft_datetimepicker {
    padding: 4px;
}
.xdsoft_datetimepicker .xdsoft_label {
    font-size: 12px;
}
.xdsoft_datetimepicker .xdsoft_datepicker {
    margin-left: 0;
    width: auto;
}
.xdsoft_datetimepicker .xdsoft_month {
    text-align: left;
    width: 80px;
}
.xdsoft_datetimepicker .xdsoft_timepicker {
    margin-left: 6px;
    width: auto;
}`

custom.js

jQuery('document').ready(function(){
    jQuery('.datetimepicker').datetimepicker({
        inline:true
    });
});
##

**Comment by aristath** [comment] 2016-03-26 17:27
I've been thinking a lot about this, and we have to do it some other way...

The problem is that WordPress core already include jQueryUI datepicker, the only thing missing from that is the time.
So it's preferable to use the WordPress-Core-included files than enqueuing yet another script.

I'll start working on it now, see if I can come up with some reasonable solution without including the datetimepicker script.

**Comment by alhoseany** [comment] 2016-03-26 23:54
i agree. i needed the time picker because the client needed it. i have added another customization to the customizer. i added a language selector like the one WPML add in the admin bar.

here is a screen shot:
http://take.ms/VOWp7

**Comment by ReyMarval** [comment] 2016-04-16 21:30
A date picker, would be awesome on kirki.

**Comment by ReyMarval** [comment] 2016-05-05 04:27
Needing it :(

**Comment by aristath** [comment] 2016-05-09 16:17
@ReyMarval a `date` control has been available in the last 2 versions but there was a typo that was preventing it from properly working.
Please pull the latest `develop` branch and use `date` as your control type, the bug has been fixed and will be included in the next stable release.

**Comment by aristath** [comment] 2017-05-14 09:53
Closing this one, the date control works fine in the develop branch.

**Closed as completed by aristath** 2017-05-14 09:53 UTC
Labels: feature
