### ISSUE TITLE
Typography Control doesn't trigger Save button for the second time

### ISSUE THREAD

**Issue by manandharsudin** [themeum/kirki#751] opened 2016-03-21 05:18 UTC
Hi @aristath,
### Issue description:

> > The issues is the typography field works for the first time. After selecting font and save for the first time then again changing fonts for the second time doesn't change "Save" button to "Save & Publish". If the we have to change the different for the second time we have to refresh customizer to save it. Can you please look at this.
### Version used:

> > 2.2.4
### Using theme_mods or options?

> > theme_mods
### Code to reproduce the issue (config + field(s))

> > Kirki::add_field( 'my_config', array(
> >         'type'        => 'typography',
> >         'settings'    => 'h1_font',
> >         'label'       => __( 'H1 Font' ),
> >         'section'     => 'typography_section',
> >         'default'     => array(
> >             'font-family'    => 'Source Sans Pro',
> >             'variant'        => 'regular',
> >         ),
> >     ) );

Thanks

**Comment by aristath** [comment] 2016-03-21 23:19
Hey there!

Yes, that's a known bug. I've tried to resolve it but so far I've been unable to find a solution.
If you want to contribute I've posted a bounty on https://www.bountysource.com/issues/31575403-typography-control-does-not-apply-changes-after-save?utm_campaign=plugin&utm_content=tracker%2F2030945&utm_medium=issues&utm_source=github
If you add anything to that bounty hopefully someone will be able help us fix it.

Closing as a duplicate of https://github.com/aristath/kirki/issues/717

**Closed as completed by aristath** 2016-03-21 23:19 UTC
Labels: duplicate
