### ISSUE TITLE
Is it possible to use transport => refresh to display content added with Action Hooks

### ISSUE THREAD

**Issue by kevinmamaqi** [themeum/kirki#1989] opened 2018-09-24 18:53 UTC
### Issue description:
I am trying to modify the appearance of some elements added via hook with the sortable field, but, when I move them the page refreshes but the elements won't appear. When I fully refresh the page it works fine.

### Version used:
Latest from WP

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'my_theme', array(
	'type'        => 'sortable',
	'settings'    => 'my_layout',
	'label'       => __( 'Sort and display', 'my_theme' ),
	'section'     => 'my_section',
	'default'     => array(
		'template_title',
		'template_excerpt',
		'template_comments',
		'template_votes',
	),
	'choices'     => array(
		'template_title' => esc_attr__( 'Title', 'my_theme' ),
		'template_excerpt' => esc_attr__( 'Excerpt', 'my_theme' ),
		'template_comments' => esc_attr__( 'Comments', 'my_theme' ),
		'template_votes' => esc_attr__( 'Votes', 'my_theme' ),
	),
	'transport'	  => 'refresh',
) );
```

```
$layout_elements = get_theme_mod( 'my_layout', array(
	'template_title',
	'template_excerpt',
	'template_comments',
	'template_votes',
	)
);

if ( ! empty( $layout_elements ) && is_array( $layout_elements ) ) {
    foreach ( $layout_elements as $element ) {
      add_action( 'my_template',''.$element.'');
    }
}
```

**Comment by aristath** [comment] 2018-10-01 16:53
Closing as a duplicate of https://wordpress.stackexchange.com/questions/315546/add-action-dont-updates-theme-layout-when-using-values-from-the-wordpress-custo

**Closed as completed by aristath** 2018-10-01 16:53 UTC
